Visual Project/Models/Guest.cs
using BCrypt.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Visual_Project.Models
{
    public class Guest:EndUser
    {
       
        public virtual ICollection<Reservation> Reservations { get; set; }=new List<Reservation>();

        //public static void AddGuest(Guest guest)
        //{
        //    var _context = HotelDbContext.GetService(typeof(HotelDbContext));
        //    using (HotelDbContext dbContext = new HotelDbContext())
        //    {

               
        //        guest.Password = BCrypt.Net.BCrypt.EnhancedHashPassword(guest.Password, 13);
        //        dbContext.Guests.Add(guest);
        //        dbContext.SaveChanges();
        //    }
        
        //}

        //public static bool UserLogin(Guest guest)
        //{
        //    using (HotelDbContext dbContext = new HotelDbContext())
        //    {
        //        var cnt = dbContext.Guests.Where(gst => gst.Username == guest.Username && gst.Password == guest.Password).Count();
        //        return cnt > 0;

                
        //    }

        //}
    }
}

Visual Project/Models/Room.cs
using System.ComponentModel.DataAnnotations;
using static Visual_Project.Models.EndUser;

namespace Visual_Project.Models
{
    public class Room
    {
        [Key]
        [Required]
        [RegularExpression("[0-9]")]
        [UniqueRoomId(ErrorMessage = "This Room ID already in use. Please choose a different ID.")]
        public string ID { get; set; }
        [Required]
        [Range(1, int.MaxValue)]
        public int Floor { get; set; }
        [Required]
        [Range(0.01, double.MaxValue)]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        [Required]
        [Range(1, 5)]
        public int Rate { get; set; }
        [Required]
        public string View { get; set; }
        [Required]
        public int RoomClassID { get; set; }
        public virtual RoomClass RoomClass { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

        //      public static int Rooms()
        //{
        //	using HotelDbContext DbContext = new();
        //	{
        //		return DbContext.Rooms.Count();

        //          }


        //}

        public class UniqueRoomIdAttribute : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                var context = (HotelDbContext)validationContext.GetService(typeof(HotelDbContext)); // Replace YourDbContext with the actual DbContext class name
                var roomId = value.ToString();
                var existingUser = context.Rooms.FirstOrDefault(RoomId => RoomId.ID == roomId);

                if (existingUser != null)
                {
                    return new ValidationResult(ErrorMessage);
                }

                return ValidationResult.Success;
            }
        }
    }
}

Visual Project/Models/RoomViewModel.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Visual_Project.Models
{
    public class RoomViewModel
    {
       
        public string RoomID { get; set; }

       
        public int Floor { get; set; }

       
        public decimal Price { get; set; }

      
        public int Rate { get; set; }
        public string View { get; set; }
        public string RoomType { get; set; }
        public string Description { get; set; }
     
        public int NumOfBeds { get; set; }
      
        public string Check_inDate { get; set; }
     
        public string Check_OutDate { get; set; }
        //public static void AddRoom(RoomViewModel room)
        //{
        //    using (HotelDbContext dbContext = new HotelDbContext())
        //    {
        //        var roomclassid = (from roomclass in dbContext.RoomClasses
        //                           where roomclass.Type == room.RoomType
        //                           select roomclass.ID).First();

        //        Room RoomToAdd = new() {ID=room.RoomID,
        //            Floor=room.Floor,
        //            Price=room.Price,
        //            Rate=room.Rate,
        //            RoomClassID=roomclassid,
        //            View=room.View,
        //          };

        //        dbContext.Rooms.Add(RoomToAdd);
        //        dbContext.SaveChanges();
        //    }
        //}
        //public static List<RoomViewModel> Result(RoomViewModel search)
        //{
        //    using (HotelDbContext dbContext = new HotelDbContext())
        //    {

        //        DateTime From = DateTime.Parse(search.Check_inDate),To= DateTime.Parse(search.Check_OutDate);
        //       // Console.WriteLine(from);
        //        var roomclassid = (from roomclass in dbContext.RoomClasses
        //                           where roomclass.Type == search.RoomType
        //                           select roomclass.ID).First();


        //        var availableRooms = dbContext.Rooms
        //       .Include(r => r.Reservations)
        //       .Where(room => room.Reservations.All(reservation =>
        //       reservation.CheckOutDate <= From
        //       || reservation.CheckInDate >=To)
        //       && room.RoomClassID == roomclassid)
        //       .ToList();
        //    //  foreach (var room in availableRooms) Console.WriteLine(room.Reservations.First().Check_outDate);

        //        var rooms = (from room in availableRooms
        //                     join roomclass in dbContext.RoomClasses
        //                     on room.RoomClassID equals roomclass.ID
        //                     where room.RoomClassID == roomclassid
        //                     && room.Price <= search.Price
        //                     && room.Rate == search.Rate
        //                     && room.View == search.View
        //                     select new RoomViewModel {
        //                         RoomID = room.ID,
        //                         Price =room.Price,
        //                         Rate=room.Rate,
        //                         View=room.View,
        //                         RoomType=roomclass.Type,
        //                         NumOfBeds=roomclass.NumOfBeds,
        //                         Description=roomclass.Description,

        //                     }).ToList();

              
        //        return rooms;
        //    }

        //}
    }
}

Visual Project/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Specialized;
using System.Runtime.Intrinsics.Arm;
using Visual_Project.Models;

namespace Visual_Project.Controllers
{
    public class RoomsController : Controller
    {
        private readonly HotelDbContext dbContext;
        public RoomsController(HotelDbContext context)
        {
            dbContext = context;
        }
       // HotelDbContext dbContext =new(); 
        public IActionResult Search()
        {
            return View();
        }
        public IActionResult Results()
        {
            return View();
        }
        [HttpGet]
        public IActionResult BookingPeriod()
        {
            return View();
        }

        public IActionResult BookingPeriod(RoomViewModel room)
        {
            HttpContext.Session.SetString("CheckInDate", room.Check_inDate);
            HttpContext.Session.SetString("CheckOutDate", room.Check_OutDate);
            return RedirectToAction("Search");
        }
        [HttpPost]
		public IActionResult Search(RoomViewModel room)
            
		{
  
                room.Check_inDate = HttpContext.Session.GetString("CheckInDate");
                room.Check_OutDate = HttpContext.Session.GetString("CheckOutDate");

                List<RoomViewModel> Results = new();
             
                DateTime From = DateTime.Parse(room.Check_inDate), To = DateTime.Parse(room.Check_OutDate);
                
                var roomclassid = (from roomclass in dbContext.RoomClasses
                                   where roomclass.Type == room.RoomType
                                   select roomclass.ID).First();


                var availableRooms = dbContext.Rooms
               .Include(r => r.Reservations)
               .Where(room => room.Reservations.All(reservation =>
               reservation.CheckOutDate <= From
               || reservation.CheckInDate >= To)
               && room.RoomClassID == roomclassid)
               .ToList();

            /*
            var cart = HttpContext.Session.Get<List<Room>>("ShoppingCart") ?? new List<Room>();
            var resultRooms = availableRooms.Where
            (room => !cart.Any
            (excludedRoom =>
            excludedRoom.ID == room.ID)).ToList();
             */
            var rooms = (from rom in availableRooms
                             join roomclass in dbContext.RoomClasses
                             on rom.RoomClassID equals roomclass.ID
                             where rom.RoomClassID == roomclassid
                             && rom.Price <= room.Price
                             && rom.Rate == room.Rate
                             && rom.View == room.View
                             select new RoomViewModel
                             {
                                 RoomID = rom.ID,
                                 Price = rom.Price,
                                 Rate = rom.Rate,
                                 View = rom.View,
                                 RoomType = roomclass.Type,
                                 NumOfBeds = roomclass.NumOfBeds,
                                 Description = roomclass.Description,

                             }).ToList();


                Results = rooms;
               
                return View("Results", Results);
          

		}
		public IActionResult AddToCart(string id)

		{
           
                var username = HttpContext.Session.GetString("Username");

                var user = dbContext.Guests.FirstOrDefault(u => u.Username == username);
                var CartItem = (from room in dbContext.Rooms
                                where room.ID == id
                                select room).First();

                var cart = HttpContext.Session.Get<List<Room>>("ShoppingCart") ?? new List<Room>();
                cart.Add(CartItem);
                HttpContext.Session.Set("ShoppingCart", cart);

                return RedirectToAction("Search", "Rooms");
            //}
            //return View();
		}

	}
}

Visual Project/Controllers/StatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Visual_Project.Models;

namespace Visual_Project.Controllers
{
    public class StatisticsController : Controller
    {
        private readonly HotelDbContext DbContext;
        public StatisticsController(HotelDbContext context)
        {
            DbContext = context;
        }
        public IActionResult Statistics()
        {
            //ViewBag.Occupied=Reservation.OccupiedRooms()*1.0/Room.Rooms()*100;
            int NumOfRooms = 0;
            DateTime date = DateTime.Now;
            var result = DbContext.Reservations
                          .Where(res => date >= res.CheckInDate && date <= res.CheckOutDate)
                          .Include(res => res.Rooms)
                          .ToList();
            foreach (var reservation in result)
            {
                NumOfRooms += reservation.Rooms.Count();
            }
           
            ViewBag.Occupied = NumOfRooms * 1.0 / DbContext.Rooms.Count() * 100;
            return View();
        }
        [HttpGet]
        public IActionResult Date()
        {
            return View();
        }
       [HttpPost]
        public IActionResult Date(Reservation reservation)

        {
           
                reservation.CheckInDate = DateTime.Parse(reservation.CheckIn);
                reservation.CheckOutDate = DateTime.Parse(reservation.CheckOut);
            Console.WriteLine(reservation.CheckInDate);
                var result = (from res in DbContext.Reservations
                              where reservation.CheckInDate <= res.CheckInDate && reservation.CheckOutDate >= res.CheckOutDate
                              select res).ToList();
                return View("DateResults", result);
          
        }
        public IActionResult Guest()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Guest(Reservation reservation)
        {
           
                var result = (from res in DbContext.Reservations
                              where reservation.GuestID == res.GuestID
                              select res).ToList();
                return View("GuestResults", result);
            
        }
        [HttpGet]
        public IActionResult Rooms()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Rooms(string id)
        {
           
                var result = DbContext.Reservations
                                  .Include(res => res.Rooms.Where(room => room.ID == id))
                                  .ToList();
                return View("RoomResults", result);
           
        }
        
    }

}

Visual Project/Views/Statistics/Date.cshtml
@model Reservation
@{
}
<head>
    <title>Filter By Date</title>
</head>
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0" style="background-image: url(../img/carousel-1.jpg);">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Filter By Date</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Filter By Date</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->

<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 mt-5">
            <div class="m-auto col-lg-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <form asp-action="Date" method="post">
                        <div class="row g-3">
                        
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="checkin" name="checkin" asp-for="@Model.CheckIn">
                                    <label for="checkin">Date From</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="checkout" name="checkout" asp-for="@Model.CheckOut">
                                    <label for="checkout">Date To</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">
                                    Filter
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Visual Project/Views/Statistics/DateResults.cshtml
@model List<Reservation>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0"
     style="background-image: url(../img/carousel-1.jpg)">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">
                Results
            </h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active"
                        aria-current="page">
                        Results
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Admin Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 mt-5">
            <div class="m-auto col-lg-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">

                    <div class="row g-3">
                        <table>
                            <thead>
                                <tr>
                                    <th>Reservation ID</th>
                                    <th>Check in Date</th>
                                    <th>Check out Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var result in Model)
                                {
                                    <tr>
                                        <td>@result.ID</td>
                                        <td>@result.CheckInDate</td>
                                        <td>@result.CheckOutDate</td>
                                    </tr>
                                   
                                }
                            </tbody>

                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>
</div>
<!-- Admin End -->

Visual Project/Views/Statistics/Guest.cshtml
@model Reservation
@{
}
<head>
    <title>Filter By Date</title>
</head>
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0" style="background-image: url(../img/carousel-1.jpg);">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Filter By Guest</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Filter By Guest</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->

<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 mt-5">
            <div class="m-auto col-lg-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <form asp-action="Guest" method="post">
                        <div class="row g-3">

                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="GuestID" name="GuestID" asp-for="@Model.GuestID">
                                    <label for="GuestID">Guest ID</label>
                                </div>
                            </div>
              
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">
                                    Filter
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Visual Project/Views/Statistics/GuestResults.cshtml
@model List<Reservation>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0"
     style="background-image: url(../img/carousel-1.jpg)">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">
                Results
            </h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active"
                        aria-current="page">
                        Results
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Admin Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 mt-5">
            <div class="m-auto col-lg-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">

                    <div class="row g-3">
                        <table>
                            <thead>
                                <tr>
                                    <th>Reservation ID</th>
                                    <th>Guest ID</th>
                                    <th>Check in Date</th>
                                    <th>Check out Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var result in Model)
                                {
                                    <tr>
                                        <td>@result.ID</td>
                                        <td>@result.GuestID</td>
                                        <td>@result.CheckInDate</td>
                                        <td>@result.CheckOutDate</td>
                                    </tr>

                                }
                            </tbody>

                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>
</div>
<!-- Admin End -->

Visual Project/Views/Statistics/RoomResults.cshtml
@model List<Reservation>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0"
     style="background-image: url(../img/carousel-1.jpg)">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">
                Results
            </h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active"
                        aria-current="page">
                        Results
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Admin Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 mt-5">
            <div class="m-auto col-lg-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">

                    <div class="row g-3">
                        <table>
                            <thead>
                                <tr>
                                    <th>Reservation ID</th>
                                    <th>Check in Date</th>
                                    <th>Check out Date</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var result in Model)
                                {
                                    <tr>
                                        <td>@result.ID</td>
                                        <td>@result.CheckInDate</td>
                                        <td>@result.CheckOutDate</td>
                                    </tr>

                                }
                            </tbody>

                        </table>

                    </div>

                </div>
            </div>
        </div>

    </div>
</div>
<!-- Admin End -->

Visual Project/Views/Statistics/Rooms.cshtml
@model Reservation
@{
}
<head>
    <title>Filter By Room</title>
</head>
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0" style="background-image: url(../img/carousel-1.jpg);">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Filter By Room</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Filter By Room</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->

<div class="container-xxl py-5">
    <div class="container">
        <div class="row g-5 mt-5">
            <div class="m-auto col-lg-6">
                <div class="wow fadeInUp" data-wow-delay="0.2s">
                    <form asp-action="Rooms" method="post">
                        <div class="row g-3">

                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="RoomID" name="id">
                                    <label for="RoomID">Room ID</label>
                                </div>
                            </div>
                           
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">
                                    Filter
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Visual Project/Views/Statistics/Statistics.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<head>
    <title>Statistics</title>
</head>

<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0" style="background-image: url(../img/carousel-1.jpg);">
    <div class="container-fluid page-header-inner py-5">
        <div class="container text-center pb-5">
            <h1 class="display-3 text-white mb-3 animated slideInDown">Statistics</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb justify-content-center text-uppercase">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item text-white active" aria-current="page">Statistics</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Service Start -->
<div asp-validation-summary="All"></div>
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title text-center text-primary text-uppercase">Statistics</h6>
            <h1 class="mb-5">Occupancy Rate <span class="text-primary text-uppercase">@ViewBag.Occupied %</span></h1>
        </div>
        <div class="row g-4">
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                <a class="service-item rounded" asp-controller="Statistics" asp-action="Date">

                    <h5 class="mb-3">Filter By Date</h5>
                  
                </a>
            </div>
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
                <a class="service-item rounded" asp-controller="Statistics" asp-action="Guest">

                    <h5 class="mb-3">Filter By Guest</h5>
                  
                </a>
            </div>
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                <a class="service-item rounded" asp-controller="Statistics" asp-action="Rooms">

                    <h5 class="mb-3">Filter By Room</h5>
                  
                </a>
            </div>
           
        </div>
    </div>
</div>
<!-- Service End -->